image: skasperski/slam3d-ci

binaries:
   script:
   - mkdir build
   - cd build
   - cmake ..
   - make

pages:
   script:
   - doxygen Doxyfile
   - rm -rf /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
   - mkdir -p /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
   - mv doc/* /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
 
