image: d-reg.hb.dfki.de:5000/slam3d/ci-plain

binaries:
   stage: build
   script:
   - mkdir build
   - cd build
   - cmake ..
   - make
   artifacts:
     paths:
     - build/
   only:
   - master

pages:
   stage: deploy
   script:
   - doxygen Doxyfile
   - rm -rf /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
   - mkdir -p /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
   - mv doc/* /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
   artifacts:
     paths:
     - doc/
   only:
   - master

tests:
   stage: test
   dependencies: 
   - binaries
   script:
   - cd build
   - make test
   only:
   - master

software_catalogue_entry:
   image: d-reg.hb.dfki.de:5000/ubuntu:overview_generator
   stage: deploy
   script:
   - apt update
   - apt install -y wget
   - wget http://bob.dfki.uni-bremen.de/software_overview/generate.sh
   - sh generate.sh $CI_PROJECT_NAMESPACE $CI_PROJECT_NAME $CI_PROJECT_URL
   only:
   - master

